"""Build the self-contained Era enchant catalog from cached Wowhead facts."""
import html, json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / '.release/enchant-research'
def clean(s):
    return ' '.join(html.unescape(re.sub('<[^>]*>', ' ', s)).split())
def lua(v):
    if isinstance(v, dict): return '{'+','.join('['+lua(k)+']='+lua(x) for k,x in v.items())+'}'
    if isinstance(v, list): return '{'+','.join(map(lua,v))+'}'
    if isinstance(v, str): return json.dumps(v,ensure_ascii=False)
    return str(v)
def build():
    recipes, materials = [], {}
    for row in json.loads((CACHE/'list.json').read_text(encoding='utf8')):
        sid=row['id']; text=(CACHE/f'{sid}.html').read_text(encoding='utf8'); gathered={}
        for m in re.finditer(r'WH.Gatherer.addData\((\d+),\s*4,\s*',text):
            data=json.JSONDecoder().raw_decode(text[m.end():])[0]
            gathered.setdefault(int(m[1]),{}).update(data)
        fact=gathered[6][str(sid)]
        tooltip=json.loads(re.search(r'g_spells\['+str(sid)+r'\]\.tooltip_enus\s*=\s*("(?:\\.|[^"\\])*")',text)[1])
        effect=re.search(r'Enchant Item:\s*<span[^>]*>(.*?)</span>&nbsp;\((\d+)\)',text)
        assert effect, sid
        requirement=re.search(r'Requires Enchanting \((\d+)\)',text)
        skill=int(requirement[1]) if requirement else max(1,row['colors'][0])
        minimum=re.search(r'(?:level (\d+) or higher item|item.*?level (\d+) or higher)',clean(tooltip),re.I)
        tool=re.search(r'Tools:.*?item=(\d+)[^>]*>(.*?)</a>',tooltip)
        slot=row['name'].split(' - ')[0].replace('Enchant ','')
        level=1 if skill<=50 else 10 if skill<=100 else 20 if skill<=150 else 30 if skill<=200 else 40 if skill<=250 else 50 if skill<=290 else 60
        rec=dict(spellId=sid,name=row['name'],slot=slot,enchantId=int(effect[2]),effect=clean(effect[1]),
                 description=clean(fact['description_enus']),icon=fact['icon'],skill=skill,level=level,
                 gearLevel=int(next(x for x in minimum.groups() if x)) if minimum else 1,
                 reagents=row['reagents'],tool=clean(tool[2]) if tool else '')
        recipes.append(rec)
        for iid,qty in row['reagents']:
            item=gathered[3][str(iid)]
            materials[iid]=dict(itemId=iid,name=item['name_enus'],icon=item['icon'])
    facts={'source':'https://www.wowhead.com/classic/spells/professions/enchanting?filter=16;1;0',
           'recipes':recipes,'materials':materials}
    dest=ROOT/'reference/research/enchants.json';dest.write_text(json.dumps(facts,indent=2)+'\n',encoding='utf8')
    output=['-- Generated by scripts/build_enchants.py from cached Classic Era spell pages.','local _, A = ...','A.Data.Enchants={recipes={']
    output.extend('    '+lua(r)+',' for r in recipes)
    output.extend(['},materials='+lua(materials)+'}',''])
    (ROOT/'Data/Enchants.lua').write_text('\n'.join(output),encoding='utf8')
    print(f'{len(recipes)} enchant recipes; {len(materials)} materials')
if __name__=='__main__': build()
