"""Build Classic Era tooltip facts from the audited, cached sources.

Petopia Classic overrides vanilla server flags. Wowhead's pre-1.15 additions
extend coverage, but never override vanilla flags (its Classic data includes SoD).
"""
import json
import re
from pathlib import Path
from bs4 import BeautifulSoup

ROOT=Path(__file__).resolve().parents[1]
research=ROOT/'reference/research'
classic=json.loads((research/'classic-beast-flags.json').read_text())
petopia=json.loads((ROOT/'reference/pet-guide.json').read_text(encoding='utf8'))
wowhead={}
excluded=[]
for file,tameable in [('wowhead-tamable',True),('wowhead-untamable',False)]:
    raw=(research/(file+'.html')).read_text(encoding='utf8')
    raw=raw[raw.index('new Listview('):]
    assert '"_truncated"' not in raw.split('"data":')[0]
    rows,_=json.JSONDecoder().raw_decode(raw[raw.index('"data":')+7:])
    for row in rows:
        if row['firstseenpatch']>=11500: excluded.append(row['id']); continue
        wowhead[row['id']]=dict(row,tameable=tameable)

records={}
conflicts=[]
for id,record in classic.items():
    id=int(id)
    if '[UNUSED]' in record['name'] or 'test' in record['name'].lower() or id==2: continue
    tameable=bool(record['flags']&1 and record['family'])
    records[id]=dict(name=record['name'],tameable=tameable,source='vanilla')
    if id in wowhead and tameable!=wowhead[id]['tameable']:
        conflicts.append(dict(npcId=id,name=record['name'],vanilla=tameable,wowhead=wowhead[id]['tameable'],resolution='vanilla'))
for id,record in wowhead.items():
    if id not in records and 'test' not in record['name'].lower() and '[UNUSED]' not in record['name']:
        records[id]=dict(name=record['name'],tameable=record['tameable'],source='wowhead-pre-sod')
for pet in petopia['pets']:
    id=pet.get('npcId')
    if not id:
        matches=[i for i,r in records.items() if r['name'].lower()==pet['name'].lower()]
        if len(matches)==1: id=matches[0]
    if not id: continue
    previous=records.get(id)
    if previous and previous['tameable']!=pet['tameable']:
        conflicts.append(dict(npcId=id,name=pet['name'],vanilla=previous['tameable'],petopia=pet['tameable'],resolution='petopia-classic'))
    records[id]=dict(name=pet['name'],tameable=pet['tameable'],abilities=pet['abilities'],source='petopia-classic')

soup=BeautifulSoup((ROOT/'reference/pet-guide/abilities.html').read_text(),'html.parser')
icons={}
for ability in petopia['abilities']:
    link=soup.select_one('a[href="#'+ability['id']+'"] img')
    assert link,ability['id']
    icons[ability['name']]=Path(link['src']).stem

def lua(value):
    if value is True: return 'true'
    if value is False: return 'false'
    if isinstance(value,str): return json.dumps(value,ensure_ascii=False)
    if isinstance(value,list): return '{'+','.join(lua(x) for x in value)+'}'
    if isinstance(value,dict): return '{'+','.join('['+lua(k)+']='+lua(v) for k,v in value.items())+'}'
    return str(value)

runtime={id:{k:v for k,v in r.items() if k!='source'} for id,r in sorted(records.items())}
(ROOT/'Data/Beasts.lua').write_text('-- Generated by scripts/build_beast_catalog.py; see reference/research/beast-audit.json.\nlocal _,addon=...\naddon.Data.Beasts='+lua(runtime)+'\naddon.Data.PetSkillIcons='+lua(icons)+'\n',encoding='utf8')
audit=dict(checkedOn='2026-09-28',scope='Classic Era / Hardcore; not Season of Discovery',
           total=len(records),tamable=sum(r['tameable'] for r in records.values()),
           unknownSkillSets=[id for id,r in records.items() if r['tameable'] and 'abilities' not in r],
           excludedSeasonalIds=sorted(excluded),conflicts=conflicts,records=records,
           sources=['https://www.wow-petopia.com/classic/',
                    'https://www.wowhead.com/classic/npcs/beasts?filter=52;-2323;0',
                    'https://www.wowhead.com/classic/npcs/beasts?filter=52;-2324;0',
                    'https://github.com/cmangos/classic-db/blob/master/Full_DB/ClassicDB_1_12_1_z2815.sql.gz'])
(research/'beast-audit.json').write_text(json.dumps(audit,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
print('Beasts:',audit['total'],'tamable:',audit['tamable'],'unknown skill sets:',len(audit['unknownSkillSets']),'source conflicts:',len(conflicts))
