"""Generate Classic Era spell rank facts used by the Mage assistant's estimates.

Source: WoWSims Classic's spell implementations (not SoD/TBC).
Only numerical spell facts are extracted; no simulator code is embedded.
"""
import json
import re
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
REVISION = "7779ebbf79dc7f1341e6ab939b28a3402c9a730a"
BASE = f"https://raw.githubusercontent.com/wowsims/classic/{REVISION}/sim/mage/"
SPELLS = [
    ("fireball", "Fireball", "fireball", 3, 3.5, 1),
    ("frostbolt", "Frostbolt", "frostbolt", 5, 3, .814),
    ("scorch", "Scorch", "scorch", 3, 1.5, .429),
    ("fire_blast", "FireBlast", "fireblast", 3, 0, .429),
    ("arcane_missiles", "ArcaneMissiles", "missiles", 7, 5, .24),
    ("pyroblast", "Pyroblast", "pyroblast", 3, 6, 1),
    ("arcane_explosion", "ArcaneExplosion", "explosion", 7, 0, .143),
    ("blizzard", "Blizzard", "blizzard", 5, 8, .333),
    ("flamestrike", "Flamestrike", "flamestrike", 3, 3, .157),
    ("blast_wave", "BlastWave", "blastwave", 3, 0, .193),
]

def build():
    rows = []
    for filename, prefix, key, school, cast, coeff in SPELLS:
        source = urlopen(BASE + filename + ".go", timeout=30).read().decode()
        def values(suffix):
            match = re.search(r"^var " + prefix + suffix + r" = [^\n{]*(\{[^\n]+\})", source, re.M)
            if not match:
                return None
            raw = match[1].replace("{", "[").replace("}", "]")
            raw = re.sub(r"(?<![\d])\.(\d)", r"0.\1", raw)
            return json.loads(raw)
        ids, levels, mana = values("SpellId"), values("Level"), values("ManaCost")
        damages = values("BaseDamage") or values("BaseTickDamage")
        coefficients, casts, dots = values("SpellCoeff"), values("CastTime"), values("DotDamage")
        for rank in range(1, len(ids)):
            damage = damages[rank]
            if isinstance(damage, list):
                damage = sum(damage) / len(damage)
            seconds = casts[rank] if casts else cast
            if seconds > 100:
                seconds /= 1000
            coefficient = coefficients[rank] if coefficients else coeff
            if key == "missiles":
                damage *= seconds
                coefficient *= seconds
            rows.append(f'    [{ids[rank]}]={{key="{key}",rank={rank},level={levels[rank]},school={school},damage={damage:g},coefficient={coefficient:g},cast={seconds:g},mana={mana[rank]:g},dot={dots[rank] if dots else 0}}},')
    # Cone rank facts verified against nether.wowhead.com/classic/tooltip/spell/<id>.
    for rank, (id, level, damage, mana) in enumerate([(120,26,103,210), (8492,34,153,290),
            (10159,42,213,380), (10160,50,277,465), (10161,58,350,555)], 1):
        rows.append(f'    [{id}]={{key="cone",rank={rank},level={level},school=5,damage={damage},coefficient=0.135,cast=0,mana={mana},dot=0}},')
    (ROOT / "Data/MageRotationSpells.lua").write_text(
        '-- Generated by scripts/build_mage_rotation_data.py; Classic Era rank facts.\n'
        '-- Source: https://github.com/wowsims/classic/tree/master/sim/mage\n'
        'local _,A=...\nA.Data.MageRotationSpells={\n' + '\n'.join(rows) + '\n}\n', encoding="utf-8")

if __name__ == "__main__":
    build()
