"""Deterministic reviewed JSON -> Lua 5.1 data. Standard library only."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def runtime_data(value):
    """Keep gameplay facts; research URLs/checksums stay in development JSON."""
    if isinstance(value, list):
        return [runtime_data(v) for v in value
                if not (isinstance(v, str) and ('https://' in v or 'http://' in v))]
    if isinstance(value, str):
        return value.replace('See recipe vendors in the source.',
            'Buy the cooking recipe from a recipe vendor, or obtain the cooked fish through trading where allowed.')
    if not isinstance(value, dict):
        return value
    result = {}
    for key, child in value.items():
        if key in {'checkedOn', 'researched', 'sha256', 'demonSources'}:
            continue
        if isinstance(child, str) and ('https://' in child or 'http://' in child):
            continue
        # Pet skill sources are creature records and must remain. The top-level
        # research source list contains only URL/checksum pairs and is omitted.
        if key == 'sources' and isinstance(child, list) and child and all(
                isinstance(v, dict) and set(v).issubset({'url', 'sha256'}) for v in child):
            continue
        result[key] = runtime_data(child)
    return result

def lua(value):
    if value is None:
        return 'nil'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return '"' + ''.join('\\%03d' % ord(c) if ord(c) < 32 else
                             '\\' + c if c in '\\"' else c for c in value) + '"'
    if isinstance(value, list):
        return '{' + ','.join(lua(v) for v in value) + '}'
    return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in sorted(value.items())) + '}'

def generate():
    manifest = {}
    for source, target in [('recommendations', 'Items'), ('companions', 'Companions'),
                           ('quivers', 'Quivers'), ('presentation', 'Presentation'), ('pet-guide', 'PetGuide'),
                           ('scrolls', 'Scrolls')]:
        path = ROOT / 'reference' / (source + '.json')
        raw = path.read_bytes()
        manifest[str(path.relative_to(ROOT)).replace('\\', '/')] = hashlib.sha256(raw).hexdigest()
        data = runtime_data(json.loads(raw))
        text = '-- Generated by scripts/generate.py; edit the reviewed JSON source.\nlocal _, addon = ...\n'
        text += 'addon.Data = addon.Data or {}\naddon.Data.' + target + ' = ' + lua(data) + '\n'
        (ROOT / 'Data' / (target + '.lua')).write_text(text, encoding='utf-8', newline='\n')
    (ROOT / 'reference' / 'manifest.json').write_text(json.dumps(manifest, indent=2)+'\n', encoding='utf-8', newline='\n')
    print('Generated six embedded data modules and source checksums.')

if __name__ == '__main__':
    generate()
